[common]
  pwd_hash = "" # execute "server -ph your_password"
  log_path = "mix-socks.log"

[http]
  network   = "tcp"
  address   = ":2019"
  timeout   = "1m"
  max_conns = 1000

[tls]
  mode = "acme"  # "acme" or "static"

  [tls.acme]
    domains = ["example.com"]

  [tls.static]
    cert_path = "certs/cert.pem"
    key_path  = "certs/key.pem"
