[common]
  pwd_hash = "" # execute "client -ph your_password"
  log_path = "mix-socks.log"

[http]
  network   = "tcp"
  address   = ":443"
  timeout   = "15s"
  max_conns = 10000

[tls]
  mode = "acme"  # "acme" or "static"

  [tls.acme]
    domains = ["example.com"]

  [tls.static]
    cert_path = "certs/cert.pem"
    key_path  = "certs/key.pem"

[tunnel]
  max_buffer_size = 32768
