[common]
  password = "test"
  log_path = "mix-socks.log"

[client]
  timeout   = "1m"
  pre_conns = 64

[server]
  network = "tcp"
  address = "127.0.0.1:2019"
  root_ca = ""

[front]
  network  = "tcp"
  address  = "127.0.0.1:2020"
  username = ""
  password = ""
