[common]
  password = "test"
  log_path = "mix-socks.log"

[client]
  timeout   = "10s"
  pre_conns = 32

[server]
  network = "tcp"
  address = "1.1.1.1:443"
  root_ca = ""

[front]
  network  = "tcp"
  address  = "127.0.0.1:2026"
  username = ""
  password = ""

[tunnel]
  buffer_size  = 2048
  jitter_level = 3    # 1 - 10

[android]
  dns_server = "8.8.8.8:53"
